### ISSUE TITLE
How to render a divider/separator ?

### ISSUE THREAD

**Issue by aadrian** [onokumus/metismenu#204]
Hi,

How to render a divider/separator between menu items (and sub-items) ?

Thank you.

**Comment by onokumus** [comment]
MetisMenu does not provide a built-in divider option. Separators can be added with CSS, for example:

```css
.metismenu li + li {
    border-top: 1px solid #dee2e6;
}
```
You can also target nested menus specifically with .metismenu ul > li + li.
