### ISSUE TITLE
How to keep menu item after click?

### ISSUE THREAD

**Issue by billyaraujo** [onokumus/metisMenu#47]
I would like to know if there is a way to maintain the active menu selection after click and after losing focus.

**Comment by onokumus** [comment]
@billyaraujo 
```css
.selected {
  color: #ffaaaa;
  background-color: #eee;
}
```
```html
<li class="selected">
...
</li>
```
OR

```script
$('li.active').addClass('selected');
```
