### ISSUE TITLE
Remove collapse animation on submenu

### ISSUE THREAD

**Issue by svdg** [onokumus/metisMenu#59]
Is it possible to remove the animation from submenu's only?

**Comment by onokumus** [comment]
@svdg 
Possible. For example
### html
```html
<ul class="metismenu">
      <li>
        <a href="#">Menu</a>
        <ul>
          <li><a href="#">item</a></li>
          <li>
            <a href="#">Sub Menu</a>
            <ul class="sub-menu">
              <li><a href="#">Sub Menu item</a></li>
              <li><a href="#">Sub Menu item</a></li>
              <li><a href="#">Sub Menu item</a></li>
            </ul>
          </li>
        </ul>
      </li>
    </ul>
```

### css

```css
.metismenu .sub-menu.collapsing {
  transition: none;
}
```
#### OR

```css
.metismenu ul ul.collapsing {
  transition: none;
}
```
